service: NouriMeals-API

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-jest-plugin
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      inMemory: true

  jest:
    collectCoverage: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  environment:
    IS_OFFLINE: true
    DYNAMODB_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createUser:
    handler: src/functions/createUser.createUser
    events:
      - http:
          method: post
          cors: true
          path: /users
          request:
            schema:
              application/json: "${file(src/schema/create_user_request.json)}"
  getAllUsers:
    handler: src/functions/getAllUsers.getAllUsers
    events:
      - http:
          method: get
          cors: true
          path: /users
  getUser:
    handler: src/functions/getUser.getUser
    events:
      - http:
          method: get
          cors: true
          path: /users/{id}
  updateUser:
    handler: src/functions/updateUser.updateUser
    events:
      - http:
          method: put
          cors: true
          path: /users/{id}
  deleteUser:
    handler: src/functions/deleteUser.deleteUser
    events:
      - http:
          method: delete
          cors: true
          path: /users/{id}


resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: "${self:provider.environment.DYNAMODB_TABLE}"
        AttributeDefinitions:
          -
            AttributeName: "username"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "username"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1