service: NouriMeals-API

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-jest-plugin
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  
  serverless-offline:
    httpPort: 8000

  jest:
    collectCoverage: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    IS_OFFLINE: true
    DYNAMODB_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createUser:
    handler: src/functions/createUser.createUser
    events:
      - http:
          method: post
          cors: true
          path: /v1/users
          request:
            schema:
              application/json: "${file(src/schema/create_user_request.json)}"


resources:
  Resources:
    userTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: "${self:provider.environment.DYNAMODB_TABLE}"
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST