name: Run Tests

on:
  pull_request:
    branches:
    - master

jobs:
  buildAndTest:
    name: Build and test the pull request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: Install API Dependencies
      run: npm i

    - name: Install Serverless Globally
      run: npm i -g serverless

    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install Serverless dependencies
      run: sls dynamodb install --conceal

    - name: Check lint
      run: npm run lint

    - name: Deploy API to Dev for endpoint testing
      run: npm run deploy:dev

    - name: Run end to end tests
      run: npm run test:e2e
      env:
        API_DOMAIN_DEV: ${{ secrets.API_DOMAIN_DEV }}
        TABLE_DEV: ${{ secrets.TABLE_DEV }}
