name: Run Tests

on:
  pull_request:
    branches:
    - master

jobs:
  buildAndTest:
    name: Build and test the pull request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: Install API Dependencies
      run: npm i
    
    - name: Install Serverless dependencies
      uses: serverless/github-action@master
      with:
        args: dynamodb install --conceal

    - name: Check lint
      run: npm run lint

    - name: Deploy API to Dev for endpoint testing
      run: npm run deploy:dev

    - name: Run end to end tests
      run: npm run test:e2e
      


    
