name: Run Tests

on:
  pull_request:
    branches:
    - master

jobs:
  buildAndTest:
    name: Build and test the pull request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Install API Dependencies
      run: npm i
    
    - name: Install Serverless dependencies
      uses: serverless/github-action@master
      with:
        args: dynamodb install --conceal

    - name: Check lint
      run: npm run lint


    
