name: Test

on:
  push:
    branches:
    - ianbruce/feature/run-tests-in-cicd

jobs:
  testing:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Pull code
      uses: actions/checkout@master
    - name: Install dependencies
      run: npm ci
    - name: Download Serverless DynamoDB local libraries
      run: sls dynamodb install
    - name: Run unit tests
      run: npm run test