name: Deploy

on:
  push:
    branches:
    - ianbruce/feature/run-tests-in-cicd

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Pull code
      uses: actions/checkout@master
    - name: Install modules
      run: npm ci
    - name: Run unit tests
      run: npm run test